name: friendliai-provider
kind: model-provider
version: 1.1.0
description: Friendli Model APIs provide instant access to a curated set of models, powered by a proprietary inference stack called Friendli Engine for high-performance, cost-efficient inference.
author: FriendliAI
